In [5]:
!pip install tensorflow
import tensorflow as tf

  Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
     ------------------------------------ 272.8/272.8 MB 567.0 kB/s eta 0:00:00
     -------------------------------------- 65.5/65.5 kB 594.0 kB/s eta 0:00:00
     ------------------------------------ 422.5/422.5 kB 628.4 kB/s eta 0:00:00
     -------------------------------------- 24.4/24.4 MB 597.4 kB/s eta 0:00:00
     ---------------------------------------- 1.3/1.3 MB 657.3 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 5.6/5.6 MB 595.5 kB/s eta 0:00:00
     ---------------------------------------- 4.1/4.1 MB 625.6 kB/s eta 0:00:00
     ------------------------------------ 

In [6]:
print(tf.__version__)

2.12.0


## 1. Starting with tensorflow
#### tensor is multidiemnsional array setup

In [13]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

print(tf.config.list_physical_devices('GPU'))

from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


physical_devices = tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

[]
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13767789762628094536
xla_global_id: -1
]


In [14]:
# init a tensor
x=tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [15]:
x=tf.constant([[1,2,3], [4,5,6]])   #creating the list form
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [16]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [18]:
x = tf.eye(3)  # identical matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
x = tf.random.normal((3,3), mean=0, stddev=1
                     )
print(x)

tf.Tensor(
[[-0.9873699  -0.45874768  0.66685396]
 [ 1.4742466   0.10750124 -0.5459589 ]
 [-0.37503806 -0.9370405  -0.23495351]], shape=(3, 3), dtype=float32)


In [20]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.09475982 0.7589519  0.6327034 ]], shape=(1, 3), dtype=float32)


In [21]:
x=tf.range(start=1, limit=10, delta=2)#delta is steps
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [22]:
x=tf.cast(x, dtype=tf.float64)  #though its uncommon
# tf.float(16, 32, 64)
# tf.int(8,16,32,64)
# tf.bool
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [23]:
############mathematical operation
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])


z=tf.add(x, y)   # or z=x+y also works
print(z)
# similiary subtract(-), divide(/), multiply(*)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [24]:
z=tf.tensordot(x, y, axes=1)
z=tf.reduce_sum(x*y, axis=0)  # its name reduced sum instead of sum
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [25]:
z=x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [26]:
# matrix multiplication
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

z=tf.matmul(x, y) # method 1
print(z)
print("            ")
z=x@y             # method 2
print(z)

tf.Tensor(
[[ 0.32518876  0.29128295 -0.45695576 -1.3525047 ]
 [ 3.3381877   1.8028265   3.10041    -2.372631  ]], shape=(2, 4), dtype=float32)
            
tf.Tensor(
[[ 0.32518876  0.29128295 -0.45695576 -1.3525047 ]
 [ 3.3381877   1.8028265   3.10041    -2.372631  ]], shape=(2, 4), dtype=float32)


In [27]:
############ Indexing

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print("")
print(x[1:])
print("")
print(x[1:6])
print("")
print(x[::2])
print("")
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)

tf.Tensor([1 1 2 3 1], shape=(5,), dtype=int32)

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [28]:
indices=tf.constant([0,3])
x_ind = tf.gather(x, indices)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0, :])
print("")
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [31]:
############# Reshaping
x = tf.range(9)
x
x=tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [34]:
x=tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
